/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pemesanan_makanan;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Pemesan_Makanan extends javax.swing.JFrame {

    java.util.ArrayList<String> daftarPesanan = new java.util.ArrayList<>();
    int totalHarga = 0;

    /**
     * Creates new form Pemesan_Makanan
     */
    private void updateTampilanPesanan() {
        AreaPesanan.setText("");
        if (daftarPesanan.isEmpty()) {
            AreaPesanan.setText("Belum ada pesanan :)");
        } else {
            for (String pesanan : daftarPesanan) {
                AreaPesanan.append(pesanan + "\n");
            }
            AreaPesanan.append("\n----------------------------------------------\n");
            AreaPesanan.append("Total Harga: Rp" + totalHarga);
        }
    }

    public Pemesan_Makanan() {
        initComponents();
        DineInBtn.setSelected(true);
        DropdownKategori.addItem("Makanan");
        DropdownKategori.addItem("Minuman");
        DropdownKategori.addItem("Snack");
        DropdownNoMeja.addItem("Pilih Meja...");
        for (int i = 1; i <= 30; i++) {
            DropdownNoMeja.addItem("No. " + i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DropdownKategori = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        PesanBtn = new javax.swing.JButton();
        PesanField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListMenu = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        AreaPesanan = new java.awt.TextArea();
        jLabel6 = new javax.swing.JLabel();
        DropdownNoMeja = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TakeAwayBtn = new javax.swing.JRadioButton();
        DineInBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("No. Meja :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 140, 90, 19);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("Pemesan :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 190, 74, 19);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setText("Selamat Datang silahkan pilih menu");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 70, 450, 40);

        DropdownKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        DropdownKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropdownKategoriActionPerformed(evt);
            }
        });
        getContentPane().add(DropdownKategori);
        DropdownKategori.setBounds(110, 300, 247, 34);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("Kategori :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 300, 72, 19);

        PesanBtn.setBackground(new java.awt.Color(51, 204, 0));
        PesanBtn.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        PesanBtn.setForeground(new java.awt.Color(255, 255, 255));
        PesanBtn.setText("Pesan");
        PesanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PesanBtn);
        PesanBtn.setBounds(410, 440, 250, 40);

        PesanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PesanField);
        PesanField.setBounds(110, 190, 250, 34);

        ListMenu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListMenu);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(110, 360, 250, 120);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("CocogooseProTrial Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Geprek MYR");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 50);

        hapus.setBackground(new java.awt.Color(255, 102, 51));
        hapus.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(430, 400, 90, 23);

        tambah.setBackground(new java.awt.Color(255, 255, 102));
        tambah.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(550, 400, 90, 23);
        getContentPane().add(AreaPesanan);
        AreaPesanan.setBounds(390, 170, 270, 200);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel6.setText("Admin: 089876543210");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(480, 520, 190, 19);

        DropdownNoMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropdownNoMejaActionPerformed(evt);
            }
        });
        getContentPane().add(DropdownNoMeja);
        DropdownNoMeja.setBounds(110, 140, 250, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("Daftar Pesanan saat ini :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(390, 140, 190, 19);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setText("Menu :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 360, 50, 19);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel9.setText("Medsos: @geprekMYR_");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 520, 190, 19);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 510, 730, 40);

        TakeAwayBtn.setBackground(new java.awt.Color(0, 204, 0));
        buttonGroup1.add(TakeAwayBtn);
        TakeAwayBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TakeAwayBtn.setText("Take Away");
        TakeAwayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeAwayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(TakeAwayBtn);
        TakeAwayBtn.setBounds(130, 250, 100, 30);

        DineInBtn.setBackground(new java.awt.Color(0, 153, 153));
        buttonGroup1.add(DineInBtn);
        DineInBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        DineInBtn.setText("Dine in");
        DineInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DineInBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DineInBtn);
        DineInBtn.setBounds(260, 250, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PesanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanBtnActionPerformed
        String nomorMeja = DropdownNoMeja.getSelectedItem().toString();
        String namaPemesan = PesanField.getText();
        if (daftarPesanan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih dan tambah menu terlebih dahulu!");
            return;
        }
        if (namaPemesan.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi nama pemesan terlebih dahulu!");
            return;
        }
        String tipePesanan = "";
        if (DineInBtn.isSelected()) {
            tipePesanan = "Dine In (Makan di Sini)";
            if (nomorMeja.equals("Pilih Meja...")) {
                JOptionPane.showMessageDialog(this, "Untuk 'Dine In', harap pilih No. Meja!");
                return; // Hentikan proses
            }
        } else if (TakeAwayBtn.isSelected()) {
            tipePesanan = "Take Away (Bungkus)";
            nomorMeja = "Take Away (Tidak pakai meja)";
        }
        String struk = "Tipe Pesanan : " + tipePesanan + "\n"
                + "Nomor Meja : " + nomorMeja + "\n"
                + "Nama Pemesan : " + namaPemesan + "\n\n"
                + "Daftar Pesanan :\n" + AreaPesanan.getText();

        JOptionPane.showMessageDialog(this, struk);
    }//GEN-LAST:event_PesanBtnActionPerformed

    @SuppressWarnings("empty-statement")
    private void DropdownKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropdownKategoriActionPerformed
        String kategori = DropdownKategori.getSelectedItem().toString();
        String[] data = null;

        if (kategori.equals("Makanan")) {
            data = new String[]{
                String.format("%-45s %s", "Ayam Geprek", "Rp 7.000"),
                String.format("%-39s %s", "Nasi + Ayam Geprek", "Rp 12.000"),
                String.format("%-53s %s", "Nasi", "Rp 5.000"),
                String.format("%-32s %s", "Nasi + Ayam Geprek + Es Teh", "Rp 15.000")
            };
        } else if (kategori.equals("Minuman")) {
            data = new String[]{
                String.format("%-45s %s", "Es Coklat Milo", "Rp 12.000"),
                String.format("%-47s %s", "Teh Tarik", "Rp 10.000"),
                String.format("%-50s %s", "Es Jeruk", "Rp 5.000"),
                String.format("%-52s %s", "Es teh", "Rp 4.000")
            };
        } else if (kategori.equals("Snack")) {
            data = new String[]{
                String.format("%-45s %s", "Kulit Goreng", "Rp 10.000"),
                String.format("%-43s %s", "Usus Goreng", "Rp 10.000"),
                String.format("%-45s %s", "Sate-Satean", "Rp 2.000"),
                String.format("%-45s %s", "Gorengan", "Rp 1.000")
            };
        }
        ListMenu.setListData(data);
    }//GEN-LAST:event_DropdownKategoriActionPerformed

    private void PesanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesanFieldActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        if (daftarPesanan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih menu terlebih dahulu");
            return;
        }
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin hapus semua pesanan yang sudah ditambahkan?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            daftarPesanan.clear(); // Mengosongkan pesanan
            totalHarga = 0;
            updateTampilanPesanan();
            JOptionPane.showMessageDialog(this, "Semua daftar pesanan telah dihapus.");
    }//GEN-LAST:event_hapusActionPerformed
    }
    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        String menu = ListMenu.getSelectedValue();
        if (menu == null) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih menu terlebih dahulu");
            return;
        }
        try {
            String inputJumlah = JOptionPane.showInputDialog(this, "Masukkan jumlah porsi");
            if (inputJumlah != null && !inputJumlah.trim().isEmpty()) {
                int jumlah = Integer.parseInt(inputJumlah);

                String[] pisah = menu.split("Rp");
                String namaMenu = pisah[0].trim();

                String hargaStr = pisah[1].replace(".", "").trim();
                int hargaSatuan = Integer.parseInt(hargaStr);

                int subTotal = hargaSatuan * jumlah;
                totalHarga += subTotal;

                daftarPesanan.add("- " + namaMenu + "(" + jumlah + " porsi) = Rp" + subTotal);

                updateTampilanPesanan();
                JOptionPane.showMessageDialog(this, "Menu berhasil ditambahkan :");

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka yang valid");
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void DropdownNoMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropdownNoMejaActionPerformed

    }//GEN-LAST:event_DropdownNoMejaActionPerformed

    private void TakeAwayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeAwayBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TakeAwayBtnActionPerformed

    private void DineInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DineInBtnActionPerformed

    }//GEN-LAST:event_DineInBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemesan_Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemesan_Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemesan_Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemesan_Makanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pemesan_Makanan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea AreaPesanan;
    private javax.swing.JRadioButton DineInBtn;
    private javax.swing.JComboBox<String> DropdownKategori;
    private javax.swing.JComboBox<String> DropdownNoMeja;
    private javax.swing.JList<String> ListMenu;
    private javax.swing.JButton PesanBtn;
    private javax.swing.JTextField PesanField;
    private javax.swing.JRadioButton TakeAwayBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
